
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itzewaabnkasuvpppjsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0emV3YWFibmthc3V2cHBwanNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NjkxODMsImV4cCI6MjA2MzI0NTE4M30.jFPxYRMZBVuhKAVxJARmCvvZajB0ww0MJAuc7Rez5jM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
